/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import control.CustomerDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;

public class AplikasiUtama extends javax.swing.JFrame {
    panelCustomer customer = new panelCustomer();
    panelDetail detail = new panelDetail();
    panelPegawai pegawai = new panelPegawai();
    panelPemesanan pemesanan = new panelPemesanan();
    panelProduksi produksi = new panelProduksi();
    panelRole role = new panelRole();
    panelTransaksi transaksi = new panelTransaksi();
    DefaultTableModel dtmCust;
    CustomerDAO daoCust;
    
    public AplikasiUtama() {
        initComponents();
        this.add(customer);
        this.add(detail);
        this.add(pegawai);
        this.add(pemesanan);
        this.add(produksi);
        this.add(role);
        this.add(transaksi);
        user.setBackground(new java.awt.Color(0,0,0,1));
        pass.setBackground(new java.awt.Color(0,0,0,1));
        daoCust = new CustomerDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel12 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton5 = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Role = new javax.swing.JButton();
        Pemesanan = new javax.swing.JButton();
        Customer = new javax.swing.JButton();
        Produksi = new javax.swing.JButton();
        Pegawai = new javax.swing.JButton();
        Transaksi = new javax.swing.JButton();
        DetailPemesanan = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cust = new javax.swing.JMenuItem();
        det = new javax.swing.JMenuItem();
        peg = new javax.swing.JMenuItem();
        pem = new javax.swing.JMenuItem();
        pro = new javax.swing.JMenuItem();
        rol = new javax.swing.JMenuItem();
        tra = new javax.swing.JMenuItem();

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("____________________________________________________");

        jInternalFrame1.setVisible(true);

        jButton5.setText("jButton2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Manajemen Percetakan");
        getContentPane().setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(37, 150, 190));
        panelLogin.setLayout(new java.awt.GridBagLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 26, 0, 0);
        panelLogin.add(jLabel5, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 238, 0, 0);
        panelLogin.add(jLabel6, gridBagConstraints);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_20px_1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 37;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 36;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 15, 0, 221);
        panelLogin.add(jLabel11, gridBagConstraints);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 238, 0, 0);
        panelLogin.add(jLabel7, gridBagConstraints);

        user.setFont(user.getFont().deriveFont(user.getFont().getSize()+2f));
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 29;
        gridBagConstraints.ipadx = 239;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 243, 0, 0);
        panelLogin.add(user, gridBagConstraints);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_________________________________________");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 29;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 238, 0, 0);
        panelLogin.add(jLabel10, gridBagConstraints);

        pass.setFont(pass.getFont().deriveFont(pass.getFont().getSize()+2f));
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBorder(null);
        pass.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.ipadx = 239;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 244, 0, 0);
        panelLogin.add(pass, gridBagConstraints);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_________________________________________");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 238, 0, 0);
        panelLogin.add(jLabel9, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 118, 211));
        jButton1.setText("LOGIN");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        panelLogin.add(jButton1, gridBagConstraints);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(199, 226, 255));
        jCheckBox1.setText("Remember Password");
        jCheckBox1.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 238, 0, 0);
        panelLogin.add(jCheckBox1, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(199, 226, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Forget Password?");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 34;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 0, 0);
        panelLogin.add(jLabel14, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 154, 0);
        panelLogin.add(jLabel16, gridBagConstraints);

        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_invisible_20px_1.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 37;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 0, 0);
        panelLogin.add(disable, gridBagConstraints);

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_eye_20px_1.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 37;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 0, 0);
        panelLogin.add(show, gridBagConstraints);

        getContentPane().add(panelLogin, "card2");

        panelHome.setBackground(new java.awt.Color(37, 150, 190));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistem Manajemen Percetakan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 76, 0, 0);
        panelHome.add(jLabel3, gridBagConstraints);

        Role.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Role.setText("Role");
        Role.setBorderPainted(false);
        Role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 206;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 18, 0, 64);
        panelHome.add(Role, gridBagConstraints);

        Pemesanan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Pemesanan.setText("Pemesanan");
        Pemesanan.setBorderPainted(false);
        Pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemesananActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 32, 64);
        panelHome.add(Pemesanan, gridBagConstraints);

        Customer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Customer.setText("Customer");
        Customer.setBorderPainted(false);
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 168;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 64);
        panelHome.add(Customer, gridBagConstraints);

        Produksi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Produksi.setText("Produksi");
        Produksi.setBorderPainted(false);
        Produksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduksiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 173;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 53, 0, 0);
        panelHome.add(Produksi, gridBagConstraints);

        Pegawai.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Pegawai.setText("Pegawai");
        Pegawai.setBorderPainted(false);
        Pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PegawaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 175;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 53, 0, 0);
        panelHome.add(Pegawai, gridBagConstraints);

        Transaksi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Transaksi.setText("Transaksi");
        Transaksi.setBorderPainted(false);
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 32, 0);
        panelHome.add(Transaksi, gridBagConstraints);

        DetailPemesanan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        DetailPemesanan.setText("Detail Pemesanan");
        DetailPemesanan.setBorderPainted(false);
        DetailPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailPemesananActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 52, 32, 0);
        panelHome.add(DetailPemesanan, gridBagConstraints);

        getContentPane().add(panelHome, "card3");

        jMenu1.setText("File");

        jMenuItem3.setText("LogOut");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        cust.setText("Customer");
        cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custActionPerformed(evt);
            }
        });
        jMenu2.add(cust);

        det.setText("Detail Pemesanan");
        det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detActionPerformed(evt);
            }
        });
        jMenu2.add(det);

        peg.setText("Pegawai");
        peg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegActionPerformed(evt);
            }
        });
        jMenu2.add(peg);

        pem.setText("Pemesanan");
        pem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemActionPerformed(evt);
            }
        });
        jMenu2.add(pem);

        pro.setText("Produksi");
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        jMenu2.add(pro);

        rol.setText("Role");
        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });
        jMenu2.add(rol);

        tra.setText("Transaksi");
        tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traActionPerformed(evt);
            }
        });
        jMenu2.add(tra);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        produksix();
    }//GEN-LAST:event_proActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(this, "Good bye Admin! \nExit", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(this, "Good bye Admin! \nLogOut", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        logout();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custActionPerformed
        customerx();
    }//GEN-LAST:event_custActionPerformed

    private void detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detActionPerformed
        detailx();
    }//GEN-LAST:event_detActionPerformed

    private void pegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegActionPerformed
        pegawaix();
    }//GEN-LAST:event_pegActionPerformed

    private void pemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemActionPerformed
       pemesananx();
    }//GEN-LAST:event_pemActionPerformed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
        rolex();
    }//GEN-LAST:event_rolActionPerformed

    private void traActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traActionPerformed
        transaksix();
    }//GEN-LAST:event_traActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (user.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (pass.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Password Pinjam is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (user.getText().equals("admin")  && pass.getText().equals("admin12345*")) {
            JOptionPane.showMessageDialog(this, "Welcome admin", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            home();
        }else{
            JOptionPane.showMessageDialog(this, "Username atau Password salah", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        pass.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        pass.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void RoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleActionPerformed
        rolex();
    }//GEN-LAST:event_RoleActionPerformed

    private void PemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemesananActionPerformed
        pemesananx();
    }//GEN-LAST:event_PemesananActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        customerx();
    }//GEN-LAST:event_CustomerActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduksiActionPerformed
        produksix();
    }//GEN-LAST:event_ProduksiActionPerformed

    private void PegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PegawaiActionPerformed
        pegawaix();
    }//GEN-LAST:event_PegawaiActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        transaksix();
    }//GEN-LAST:event_TransaksiActionPerformed

    private void DetailPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailPemesananActionPerformed
        detailx();
    }//GEN-LAST:event_DetailPemesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customer;
    private javax.swing.JButton DetailPemesanan;
    private javax.swing.JButton Pegawai;
    private javax.swing.JButton Pemesanan;
    private javax.swing.JButton Produksi;
    private javax.swing.JButton Role;
    private javax.swing.JButton Transaksi;
    private javax.swing.JMenuItem cust;
    private javax.swing.JMenuItem det;
    private javax.swing.JLabel disable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField pass;
    private javax.swing.JMenuItem peg;
    private javax.swing.JMenuItem pem;
    private javax.swing.JMenuItem pro;
    private javax.swing.JMenuItem rol;
    private javax.swing.JLabel show;
    private javax.swing.JMenuItem tra;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
    private void logout() {
        jMenuBar1.setVisible(false);
        panelLogin.setVisible(true);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
    }
    
    private void home() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(true);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
    }
    
    private void customerx() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(true);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
    }
    
    private void detailx() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(true);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
    }
    
    private void pegawaix() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(true);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
    }
     
    private void pemesananx() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(true);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(false);
    }
        
    private void produksix() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(true);
        role.setVisible(false);
        transaksi.setVisible(false);
    }
        
    private void rolex() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(true);
        transaksi.setVisible(false);
    }
         
    private void transaksix() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        customer.setVisible(false);
        detail.setVisible(false);
        pegawai.setVisible(false);
        pemesanan.setVisible(false);
        produksi.setVisible(false);
        role.setVisible(false);
        transaksi.setVisible(true);
    }
    
}
